
[functions.delete-old-messages]
enabled = true
verify_jwt = true
import_map = "./functions/delete-old-messages/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/delete-old-messages/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/delete-old-messages/*.html" ]

[functions.daily-quote]
enabled = true
verify_jwt = false
# Daily quote function to fetch quotes from Gemini Flash 2.5 Lite
entrypoint = "./functions/daily-quote/index.ts"

# Note: Cron jobs need to be configured in the Supabase Dashboard
# Schedule: 0 6 * * * (daily at 6 AM UTC) for function: daily-quote
